FROM ubuntu:latest
RUN apt update && apt install openjdk-11-jdk -y && apt install maven -y
COPY . .
RUN mvn clean package -Dmaven.test.skip=true
EXPOSE 8080
CMD java -jar target/spring-backend-v1.jar
