FROM ubuntu:latest
RUN apt update
RUN apt install nodejs npm -y
RUN npm install -g @angular/cli@14.2.1
COPY . .
RUN npm install 
CMD ng build
WORKDIR /the/workdir/path
EXPOSE 80
ENTRYPOINT [ "ng serve --host 0.0.0.0 --port=80" ]